#!/usr/bin/python
# Copyright 2015 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""A python wrapper to start devappserver and a managed vm application.

Both the devappserver and the application will run in their respective
containers.
"""
# This file conforms to the external style guide
# pylint: disable=bad-indentation, g-bad-import-order

import logging
import sys
import time
import warnings

from appstart import container_sandbox
from appstart import devappserver_init
from appstart import parsing
import utils


def main():
    """Run devappserver and the user's application in separate containers.

    The application must be started with the proper environment variables,
    port bindings, and volume bindings. The devappserver image runs a
    standalone api server.
    """
    logging.getLogger('appstart').setLevel(logging.INFO)

    # args should include all the args to the sandbox, as well as a
    # parser_type arg, which indicates which subparser was used.
    args = vars(parsing.make_appstart_parser().parse_args())

    # Find out what parser was used (and remove the entry from the args).
    parser_type = args.pop('parser_type')

    # In response to 'appstart init', create a new devappserver base image.
    if parser_type == 'init':
        devappserver_init.base_image_from_dockerfile(**args)

    # In response to 'appstart run', create a container sandbox and run it.
    elif parser_type == 'run':
        sandbox = None
        success = True
        try:
            with warnings.catch_warnings():
                # Suppress the InsecurePlatformWarning generated by urllib3
                # see: http://stackoverflow.com/questions/29134512/
                warnings.simplefilter('ignore')
                sandbox = container_sandbox.ContainerSandbox(**args)
                sandbox.start()
                while True:
                    # Hacky, but it works. Note that signal.pause is not
                    # compatible with Windows...
                    time.sleep(10000)

        except KeyboardInterrupt:
            utils.get_logger().info('Exiting')
        except utils.AppstartAbort as err:
            if err.message:
                utils.get_logger().warning(str(err.message))
            success = False
        finally:
            if sandbox:
                sandbox.stop()
        if success:
            sys.exit(0)
        sys.exit(1)


if __name__ == '__main__':
    main()
